### ISSUE TITLE
Default config typos

### ISSUE THREAD

**Issue by VoidAngel** [AuraDevelopmentTeam/BungeeChat2#1]
Every message with the word "enabled" is spelled incorrectly as "enbaled" 

Example:
   enable-messager: "&eYou have &aenbaled&e messaging!"
should be
   enable-messager: "&eYou have &aenabled&e messaging!"

**Comment by shawn-ian** [comment]
GitHub :: Bug #1 Has been fixed for the 2.0.0 release. Thanks for reporting this bug!
