### ISSUE TITLE
No permission check for bungeechat global symbol

### ISSUE THREAD

**Issue by jewome62** [AuraDevelopmentTeam/BungeeChat2#103]
#### Issue Description: 
`bungeechat.command.global` is not checked is player use symbol (default config is "!" )

#### What happens:
`bungeechat.command.global` = false and player can use global chat

#### What you expected to happen:
`bungeechat.command.global` = false and player can **not** use global chat

#### Steps to reproduce:

1. `bungeechat.command.global` = false to a player or groupe no opped
2. try with player affected with this perm the message '! test'
3. See the player can talk ...
...

____
#### Affected Versions: 

- Minecraft: 1.13
![image](https://user-images.githubusercontent.com/472429/77593495-9343ef80-6ef4-11ea-8b2e-f68bb705b524.png)
rebase from master 6 days ago : https://github.com/AuraDevelopmentTeam/BungeeChat2/pull/89

#### Your most recent log or stack trace file where the issue was present: 

No stacktrace.
Config file : https://hastebin.com/rawimimugo.coffeescript

**Comment by AwesomestCode** [comment]
Submitted PR. Issue fixed.

**Comment by jewome62** [comment]
Thnaks
