### ISSUE TITLE
Adding %message% in any global chat causes the player to time out

### ISSUE THREAD

**Issue by JasonHorkles** [AuraDevelopmentTeam/BungeeChat2#106]
#### Issue Description: 
Player times out or console freezes when adding `%message%` to any global chat

#### What you expected to happen:
It should just simply send `%message%` in chat like the player wanted

#### Steps to reproduce:

1. Use any form of global chat
2. Add `%message%` to your message
3. Try to send anything else and then realize you've timed out
...

____
#### Affected Versions: 

- Minecraft: 1.15.2
- BungeeChat: 2.1.7.1067-DEV (build 57) - happened on builds before that too

**Comment by BrainStone** [comment]
Pretty sure I know what's going on here. But funny nonetheless.

**Comment by BrainStone** [comment]
Try the latest version please.

**Comment by BrainStone** [comment]
Not fixed. Need to rewrite the placeholder engine.
