### ISSUE TITLE
chat lock not working

### ISSUE THREAD

**Issue by aidplasss** [AuraDevelopmentTeam/BungeeChat2#107]
#### Issue Description: 
chat lock doesn't work ona ny server (confirmed my devs)

#### What happens:
nothing

#### What you expected to happen:
mute the chat but everyone can type

#### Steps to reproduce:

1.  fix perms
2. fix chatlock
3. 
...

____
#### Affected Versions: 

- Minecraft: 1.12
- BungeeChat:  
- Other related plugins: 

#### Your most recent log or stack trace file where the issue was present: 

```nothing comes out in logs

**Comment by BrainStone** [comment]
Turned out to be just a misconfigured config.
