### ISSUE TITLE
[feature] Customizable Error Messages

### ISSUE THREAD

**Issue by Flockcode** [AuraDevelopmentTeam/BungeeChat2#113]
Hey, once again, I'm asking for a feature.

I really like the customizability of the Plugin (Messages and more) - I would love, we could also edit the error messages. For Example "The Player is not online" etc. 
Thanks

Best wishes Hohi

**Comment by BrainStone** [comment]
What commands send that message?
And what BungeeChat version are you talking about?

**Comment by Flockcode** [comment]
Oh, I'm talking about "Could not find that Player..."

**Comment by BrainStone** [comment]
Can you please give me the exact error message?
I can't find the message.

Also what BungeeChat version?

**Comment by BrainStone** [comment]
Already implemented. For a long time actually.
