### ISSUE TITLE
Problem with cloudnet perms hook

### ISSUE THREAD

**Issue by DownStudios** [AuraDevelopmentTeam/BungeeChat2#115]
#### Issue Description: 
Can't use bungeechat even though cloudnet perms module is disabled

#### What happens:
Bungeechat is trying to hook cloudnet perms, because the cloudnetapi is still on the server and you can't remove this plugin. So the cloudnet perms module is null and bungeechat is still trying to get the user prefix

#### What you expected to happen:
I thought bungeechat is going to hook LuckPerms, because this is the active permission system.

#### Steps to reproduce:

1. Install cloudnet
2. Disable cloudnet perms in /CloudNet-Master/local/perms.yml
3. Disable the permission module in /CloudNet-Master/config.yml
4. Restart the cloudnet instance

____
#### Affected Versions: 

- Minecraft: 1.12
- BungeeChat:  2.2.0.1130
- Other related plugins: 
CloudNetAPI

#### Your most recent log or stack trace file where the issue was present: 

https://hastebin.com/afecojaquc.rb
```

**Comment by BrainStone** [comment]
Try this file: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.2.1.1132-DEV/BungeeChat-2.2.1.1132-DEV.jar

**Comment by BrainStone** [comment]
Next attempt: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.2.1.1134-DEV/BungeeChat-2.2.1.1134-DEV.jar

**Comment by BrainStone** [comment]
Fixed by d653a62
