### ISSUE TITLE
Let server handle localchat

### ISSUE THREAD

**Issue by Hugo5000** [AuraDevelopmentTeam/BungeeChat2#126]
#### Issue Description: 

I want Localchat to be handled by the server you are on, but if I disable localchat in the plugin you cant write on the server and if I enable passToClientServer the message is displayed twice

#### What happens:

The message is displayed twice when passToClientServer is set to true.

#### What you expected to happen:

That BungeeChat doesnt send the message aswell and only the local server.

#### Steps to reproduce:

1.  Enable passToClientServer for localchat
2. write something in localchat
3. 2 messages
...

____
#### Affected Versions: 

- Minecraft: 1.15
- BungeeChat:  2.2.1.1139
- Other related plugins:

**Comment by jewome62** [comment]
Since two months, the option is rename `passToBackendServer`

For me this is the normal behavior. that's noted into config file
```yaml
# This passes the chat to the servers the bungee connects to. This will cause doubled
# messages unless you block the chat on these servers or enable passTransparently
passToBackendServer=false
```

**Comment by BrainStone** [comment]
Enable this setting: https://github.com/AuraDevelopmentTeam/BungeeChat2/blob/9a4af8ca0bf70fb07a095583f8d9c56f6853ba05/src/main/resources/config.conf#L232

I believe ``passToBackendServer`` still needs to be enabled regardless.

**Comment by Hugo5000** [comment]
I am confused, there are 2 configs? a config.yml and a config.conf?

**Comment by Hugo5000** [comment]
Well this problem is resolved now, thanks for the help I didnt see the new config.conf that came with the new version, have a nice day!

**Comment by BrainStone** [comment]
As the ``.old`` in the ``config.old.yml`` indicates, the old config file is no longer in use. It's only kept for you as a backup.
