### ISSUE TITLE
Error on tab completion

### ISSUE THREAD

**Issue by AymerickA** [AuraDevelopmentTeam/BungeeChat2#134]
#### What happens:
Errors on logs when a player use TAB Complet with your plugin command (like /msg)

#### What you expected to happen:
That bug have not appear before, it's a new bug, with the same version of before, the bug appear also

#### Steps to reproduce:

1.  Just use tab complete with command of BungeeChat

____
#### Affected Versions: 

- Minecraft: 1.7-1.15 Travertine Proxy (fork of Waterfall)
- BungeeChat:  I have try with multiples versions like latest 2.2.2 like 2.1.7.1114-DEV in devbuilds
- Other related plugins: LuckPerms, LiteBans, TCPShield, Anti VPN (I list all plugins can make a conflict) Ps : I have try with no litebans and anti vpn

#### Your most recent log or stack trace file where the issue was present: 

https://framabin.org/p/?b684796248626e64#Qck6+50CCuObLBK8CyH3TjVer9HTfF1LQ2sGR49qZj8=

**Comment by BrainStone** [comment]
I think I have already fixed it. Try this version: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.2.3.1197-DEV/BungeeChat-2.2.3.1197-DEV.jar

**Comment by AymerickA** [comment]
Oh perfect, thanks

**Comment by BrainStone** [comment]
Does that fix it?

**Comment by AymerickA** [comment]
Yes it's good thanks 
(tab-complete for /msg work but exemple for /ignore don't work it's normal ?)

**Comment by BrainStone** [comment]
The command is ``/ignore add <player>``. That might be it.

**Comment by AymerickA** [comment]
Oh ok sorry, thanks
