### ISSUE TITLE
[Suggestion] Add support for punish plugins.

### ISSUE THREAD

**Issue by itaquito** [AuraDevelopmentTeam/BungeeChat2#139]
Hello!

I'm here to suggest the support of punish plugins.

What do I mean?
Many plugins have the ability to mute players (Litebans and Advancedbans for example), sadly because of the way Bungeechat works, the player can't be muted using these plugins.
This is a problem when you have a logging system on those plugins, if you mute a player using Bungeechat, the punish won't appear on the web interface of such plugins and also it won't appear on the history of the player.

What can be done to fix it?
I think a way of achieving this is by editing the database of the plugins directly.
So, when a player gets muted using Bungeechat, it will send a query to a database with specific information so the punish plugin can register it.

Another way of approaching this (and maybe even easier) is to execute a command when a player is muted by Bungeechat. Meaning that when an admin runs `/mute <player>`, Bungeechat will execute `/advancedbans:mute <player>` (for example).

Thanks!

**Comment by BrainStone** [comment]
Just turn off the BungeeChat mute module. It also should recognize most punishment plugins and disable it itself.

**Comment by itaquito** [comment]
Hum, interesting... 

This doesn't happen to me (using Advancedbans). I already tried disabling the module manually and seeing if the muting of Advancedbans works, sadly it doesn't.

Does this mean this can be a bug on Advancecbans or Bungeechat?

**Comment by BrainStone** [comment]
How did you disable the module, what did you do after that and how did you determine that it wasn't working?

**Comment by itaquito** [comment]
> How did you disable the module

```    
Muting {
        aliases {
            mute=[
                silence
            ]
            tempmute=[
                tempsilence
            ]
            unmute=[
                unsilence
            ]
        }
        blockedcommands=[
            message,
            msg,
            whisper,
            m,
            tell,
            t,
            w,
            global,
            g,
            reply,
            r
        ]
        disableWithOtherMutePlugins=true
        enabled=false
    }
```

I switch the enabled option from `true `to `false`.

> what did you do after that and how did you determine that it wasn't working?

After disabling the module, I tried muting a player with `/mute`, this time the command was recognised by AdvancedBans and it said it was successfully muted.
The muted player could still speak on the local channel. 

I re-enabled the module then I tried doing` /advancedbans:mute`. The same result.

Then I tried removing Bungeechat, the muting of Advancedbans worked again :D

**Comment by itaquito** [comment]
Yes! That was the issue.

You need to have AdvancedBans install on the proxy (Bungee) and not on the spigot servers.

Thanks for your support!
