### ISSUE TITLE
BungeeChat config not updating.

### ISSUE THREAD

**Issue by Zambosoe** [AuraDevelopmentTeam/BungeeChat2#14]
#### Issue Description: 
_When changing the config, plugin does not update._

#### What happens:
_Plugin does not update._

#### What you expected to happen:
_Uses the changes from the config._

#### Steps to reproduce:

1. _Change config._
2. _Reload /BC reload_
3. _Watch it not update lol._

____
#### Affected Versions: 

_- Minecraft: 1.12
- BungeeChat:  2.1.4.782
- Config: 10.1
- Other related plugins: BungeeDisplayName_

#### Your most recent log or stack trace file where the issue was present: 

_12:13:54 [INFO] ALERT > ~Console~: reload *Sike*_

**Comment by BrainStone** [comment]
He is talking about the formats I believe.

**Comment by shawn-ian** [comment]
Looking into it

**Comment by BrainStone** [comment]
@Zambosoe is it only the alert format?
If so disable the alert module from BungeeCord.
