### ISSUE TITLE
[Suggestion] Use vanilla chat on certain servers / Disable BungeeChat on certain servers

### ISSUE THREAD

**Issue by azridere** [AuraDevelopmentTeam/BungeeChat2#142]
While you can disable Global and Local chat on one server, what that does is simply removes the ability to speak. What I'd like added is a sort of "**server ignore**" function where bungeechat doesn't even touch that server at all. The vanilla, non-bungeechat chat system takes over instead.

**Comment by BrainStone** [comment]
You can already do that with the ``passThroughServerList`` setting.
