### ISSUE TITLE
DiscordSRV support

### ISSUE THREAD

**Issue by CodeDoctorDE** [AuraDevelopmentTeam/BungeeChat2#143]
Support for https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by AwesomestCode** [comment]
This is already working. You just need a NoChat plugin on the backend (like mine, ChatFree) and have DiscordSRV allow canceled messages. There is no possibility for native support due to us working on the bungee.

**Comment by AwesomestCode** [comment]
Also, in the future, please label your feature requests as feature requests.

**Comment by BrainStone** [comment]
What they should do or shouldn’t do is still at my discretion.
