### ISSUE TITLE
Local chat issue

### ISSUE THREAD

**Issue by Plazmotus** [AuraDevelopmentTeam/BungeeChat2#149]
#### Issue Description: 
When I give players on my server the permission "bungeechat.command.local"  they are able to talk through global chat by typing "/local \<message\>" 

#### What happens:

Players can talk in the global chat which was not intentional.

#### What you expected to happen:

Message gets sent to the local server chat.

#### Steps to reproduce:

1. Give the permission "bungeechat.command.local"
2. Type in chat "/local \<message\>

____
#### Affected Versions: 

- Minecraft: 1.15.2
- BungeeChat:  2.2.2

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/Rt0euWZj

```

**Comment by AwesomestCode** [comment]
Duplicate of #136. Patched in the latest devbuild: https://gitlab.project-creative.net/AuraDev/BungeeChat2/-/jobs/1103/artifacts/download

**Comment by BrainStone** [comment]
Duplicate of #136
