### ISSUE TITLE
Feature Request: A more advanced swear filter

### ISSUE THREAD

**Issue by JasonHorkles** [AuraDevelopmentTeam/BungeeChat2#150]
It would be nice to have more options with the swear filter, like Dyno does where you can add banned words that can either be a wildcard or match the word exactly. 
![image](https://user-images.githubusercontent.com/51760372/83956944-5b282980-a820-11ea-8777-91337a548b67.png)
This will allow certain words (like the A-word) to be only blocked if only that word is detected, rather than also blocking words like class, glass, etc.

I realize it's already an option to toggle this, but that applies to every word where it'd be nice to choose which words are banned in that way

**Comment by AwesomestCode** [comment]
This reminds me of the clbuttic mistake.

**Comment by BrainStone** [comment]
Someone's watching Tom Scott too I see.

**Comment by BrainStone** [comment]
Also considering I have more than two possible options for how to handle a swearword I don't see how I could implement that easily.

Though if I remember correctly you can use regex patterns by prefixing them with ``R=``. Then the other settings don't apply and you can be as fine grained as you like.

**Comment by JasonHorkles** [comment]
Using regex works
