### ISSUE TITLE
MarriageMaster integration

### ISSUE THREAD

**Issue by xXSchrandXx** [AuraDevelopmentTeam/BungeeChat2#16]
#### Feature request Description: 
This time it is not an Issue 😄 

I'm using [MarriageMaster](https://www.spigotmc.org/resources/marriage-master-mc-1-7-1-12.19273/) on my Server.
It would be nice if you add a %isMarried% placeholder.

could be lite this:
`PlaceHolderManager.registerPlaceholder(new PlaceHolder("%ismarried%", context -> isMarried((ProxiedPlayer) context.getSender().get()`
`  private static String isMarried(ProxiedPlayer player){
    final UUID partner = marry.DB.getPartnerUUID(player);
    if(partner != null){
      return "§4❤";
    }
    else {
        return "";
    }
  }`

Issue on my side (again) it doesn't work because it can't cast ProxiedPlayer in there.
Would be nice if you can add this or write how to get the ProxiedPlayer somhow into this Code.

**Comment by BrainStone** [comment]
MarriageMaster is a Spigot plugin if I see it correctly. So you'd need a bridge, which currently is out of scope. If MarriageMaster has PlaceholderAPI support it'll be possible in the future though.
