### ISSUE TITLE
Add option on Anti Swear

### ISSUE THREAD

**Issue by AymerickA** [AuraDevelopmentTeam/BungeeChat2#161]
I'm hoping you add option on anti swear would be a setting that allows the player to send the message but only for him and the staff (with permission).

This would allow players who disparage the server or other players to still think that their message is being sent to everyone but in reality only the staff can see it.

For example:
Player1 say "this is server is laggy and bad

Player2 don't see the message of Player1 BUT Staff1 see the message"

**Comment by AwesomestCode** [comment]
I do think that this is possible to do, my main concern is that somebody will abuse it at which point we're supporting unethical behavior. It's a similar concern to adding code to support AuthMe and things like that—we don't want to support unethical behavior. While you, in particular, may not abuse this feature, just like there are legitimate uses, we'll have to think about how other people may use this feature. While BrainStone gets the final say in everything, that's just my two cents.

**Comment by AymerickA** [comment]
I understand your opinion, I misspoke myself, some young people can be further ahead than others.

I just want to say that I'm getting tired of people who "trashtalk"/criticize without any argument.
Like "lag server" but player have 100ms...

On the other hand, I'm totally open to discussion and improvement of a server when the person gives well-founded arguments.

As far as abuse is concerned, unfortunately I could never prove anything to you, when you create a public module, you will inevitably allow one day against your will an abuse.
I never intend to do that, of course, but I can never prove it to you as you will understand it.

**Comment by AwesomestCode** [comment]
I'm sorry, I didn't mean that you're going to abuse it. I just find it it inevitable that one day, somebody will abuse such a feature. Like I said, BrainStone gets the final say in this,my thoughts are just comments and are not definitive.

**Comment by BrainStone** [comment]
Frankly I'm not a huge fan on this feature-

**Comment by BrainStone** [comment]
But to add to this I don't see any kind ethical issues with the feature whatsoever.

**Comment by AymerickA** [comment]
It's a project, if the idea doesn't seem interesting to you, do as you wish.

I just give ideas ;)

Even if you don't take my suggestion, you've already answered me many times before and I would just like to thank you for that.

**Comment by BrainStone** [comment]
Alright. As mentioned, I don't like this feature, so I will close the request.  
Though this will be possible in BungeeChat 3, as there will be a lot more customization regarding the message flow.
