### ISSUE TITLE
LocalChat doesn't work

### ISSUE THREAD

**Issue by AymerickA** [AuraDevelopmentTeam/BungeeChat2#167]
#### Issue Description: 
When global chat was disabled and local chat is per default. When a player speak that make a double speak.
The normal chat of BungeeChat broadcast in local + the default chat of server "<name>> <message>"

#### Steps to reproduce:

1. Disable global chat and set local in default
2. Speak

____
#### Affected Versions: 

- BungeeChat:  2.2.4.1263-DEV

Not need pastebin or other

So i have try the SAME config with version of BungeeChat before (2.2.4.1258-DEV) and no this bug BUT
and other bug: when a player change of server spigot, the motd + message of join was repeat like was the player join the bungee network

**Comment by BrainStone** [comment]
I'm assuming you have ``passToBackendserver`` enabled. That will make the bungee and the backend serer handle the chat and send it out.

To prevent it, either turn it off or install a NoChat plugin on all backend servers.

**Comment by AymerickA** [comment]
Yes, but this problem only on the LAST version, the version just before don't have this problem

**Comment by AymerickA** [comment]
With exactly the same config

**Comment by BrainStone** [comment]
I corrected the behavior of some settings related to that. So it's very much possible.
