### ISSUE TITLE
Fast relog, random connection lost from BungeeChat

### ISSUE THREAD

**Issue by Eisengolem** [AuraDevelopmentTeam/BungeeChat2#17]
#### What happens:

okay the main problem is that if you reconetet to fast or kick yourself with another client the bungeechat does not register you und will automaticly write in the Spigot oder Bukkit-Chat. Sometimes this problem apper suddenly without relogging.

#### Affected Versions: 

- Minecraft Bungeecord : 1.12
- BungeeChat:  
- Other related plugins: ABPS, BungeeAdminTools, BungeeTablistPlus, BungeePerms, BungeeChat, SlashServer and HubCommand

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/WLdXRRUv

```

**Comment by BrainStone** [comment]
I suppose the user gets added to the list before they removed causing them to not be on the list.

**Comment by BrainStone** [comment]
@Eisengolem if you want the fix right now, contact me on Discord.
