### ISSUE TITLE
NoSuchElementException on ChatLeave

### ISSUE THREAD

**Issue by EscolarProgramming** [AuraDevelopmentTeam/BungeeChat2#172]
#### Issue Description: 
Sometimes the exception "java.util.NoSuchElementException: No value present" gets thrown, most times on BungeeChatLeaveEvent but also on ChatEvent (like in the stacktrace I've appended below).

#### Steps to reproduce:

Unfortunately I don't know how to reproduce it, it seems to be randomly.

#### Affected Versions: 

- Minecraft: 1.16.2
- Bungee: 1.16-R0.4 Build 1536
- BungeeChat: 2.2.3.1241
- Other related plugins: --

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/SqZbhnmb

**Comment by BrainStone** [comment]
That typically happens when the associated player got deleted from the internal storage.  
Which in turn only really happens when another error appears.

So could you please check for errors from when that player joined until they left.

**Comment by BrainStone** [comment]
With the recent PR that should have been fixed alltogether. If it still happens, let me know!
