### ISSUE TITLE
mesageBlank error not functional

### ISSUE THREAD

**Issue by Xaver106** [AuraDevelopmentTeam/BungeeChat2#174]
#### Issue Description:
Sending an empty `/msg <player>` or an empty `/helpop` results in a normal error message:
- On `/helpop`: ```Incorrect usage! Use the command like this: /helpop <message>```

- On `/msg <player>`: ```Incorrect usage! Use the command like this: /msg <player> <message>```

- On `/reply`: ```Incorrect usage! Use the command like this: /reply <message>```

I could only get it to work with `/alert`(Only allert, not with aliases like /broadcast), but I got a message I couldn't find in the lang files: ```You must supply a message.```

#### What you expected to happen:
This error I found in the builtin lang files:
```messageBlank: "&cThe message cannot be blank!"```
Is this a Bug, or is this message for something else?

____
#### Affected Versions:

- Minecraft: 1.15
- BungeeChat:  2.2.4.1275-DEV

**Comment by BrainStone** [comment]
Interesting. I'm pretty sure that the message for ``/alert`` stems from Bungee itself then.

I'll look into it.

**Comment by RedstoneFuture** [comment]
Currently, with `/alert` you get the same syntax help message as `/msg`.

I think the existing `messageBlank` is a better help feedback as the command syntax if only the user forgot the <message> argument.

`messageBlank: "&cThe message cannot be blank!"`

**Comment by BrainStone** [comment]
Alright. I just verified. The `/alert` command is BungeeCord's builtin. You can disable the alert module of BungeeCord, then the alias `/alert` will be handled by BungeeChat instead and will show the correct error message.  
And the incorrect usage message is the intended one here.
