### ISSUE TITLE
My chat is Doublin

### ISSUE THREAD

**Issue by dustinduse** [AuraDevelopmentTeam/BungeeChat2#18]
#### Issue Description: 
Double chat, Caused by chat being send Local and Global

#### What happens:
14.08 18:21:03 [Server] INFO [BungeeChat] GLOBAL > DCSurvival > dustinduse: i can never talk again 
14.08 18:21:03 [Server] INFO [BungeeChat] LOCAL > DCSurvival > dustinduse: i can never talk again

#### What you expected to happen:
I expected a sandwich.

#### Steps to reproduce:

1. Global, True, default
2. Local, True
3. /g /g /g /g /g /g /g "why doesnt local work damnit" /g /g /g /g /g /g
or something like that.

____
#### Affected Versions::

- Minecraft: 1.12
- BungeeChat:  2.1.6.855

**Comment by Eisengolem** [comment]
Set Local to false

**Comment by BrainStone** [comment]
That would be a temporary solotion.
