### ISSUE TITLE
two messages with using of global-chat prefix in the global chat

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#181]
#### Issue Description: 

If I'm in the global chat and use "! + message" BungeeChat send two messages.

#### What happens:

![grafik](https://user-images.githubusercontent.com/4140635/110216463-a48cce80-7eaf-11eb-9f51-5358ed63b375.png)

#### What you expected to happen:

Only the first message is usefull.

#### Steps to reproduce:

```
    GlobalChat {
        aliases=[
            g
        ]
        default=false
        enabled=true
        # This passes the chat to the servers the bungee connects to. This will cause doubled
        # messages unless you block the chat on these servers!
        passToBackendServer=false
        # Which servers are part of the GlobalChat.
        # If it is disabled all servers are part of it.
        serverList {
            enabled=false
            list=[
                Hub1,
                Hub2,
                Hub3
            ]
        }
        symbol {
            enabled=true
            symbol="!"
        }
```

1. `/g` -> I'm in the global chat
2. `!test` or
3. `! test`

____
#### Affected Versions: 

- Minecraft: 1.16.5
- BungeeChat:  2.2.3.1241

#### Your most recent log or stack trace file where the issue was present: 

I down't get any errors in the BC / Bukkit console.

**Comment by BrainStone** [comment]
Can you check if that happens with the dev version?

**Comment by RedstoneFuture** [comment]
Unfortunately not. With version `2.2.4.1346-DEV` I have the same behavior.

![grafik](https://user-images.githubusercontent.com/4140635/111052506-8d278580-845b-11eb-9327-75ce1de6f8de.png)
![grafik](https://user-images.githubusercontent.com/4140635/111052509-9153a300-845b-11eb-83f6-a56e663d5975.png)

**Comment by Peda1996** [comment]
I can confirm this bug
