### ISSUE TITLE
Action command 

### ISSUE THREAD

**Issue by Dartume** [AuraDevelopmentTeam/BungeeChat2#185]
#### Issue Description: 
Action in the chat (command for plugin config aka UClan,Paintball....) in Globle or MulticastChat don´t work i must passToBackendServer=true and than i have all messege double thats bad 
____
#### Affected Versions: 

- Minecraft: 1.16.5
- BungeeChat:  2.2.4.1346

**Comment by BrainStone** [comment]
Install a NoChat plugin on the backend servers.  

Due to the nature of how the plugin works there is not other way to handle things.
