### ISSUE TITLE
Join and Leave Messages don't appear

### ISSUE THREAD

**Issue by JeffHD** [AuraDevelopmentTeam/BungeeChat2#188]
#### Issue Description: 

When i join or leave the server the messages doesn't show up in the players chat. All players have the bungeechat.message.join/leave/join.view/leave.view permissions. In the Bungee console it says that the message get send but none of the players receive the message. Everything worked fine on PermissonsEx but since i changed to BungeePerms it doesn't work anymore.  Is there something that could be changed in config what i haven't found jet?

#### Affected Versions:

- Minecraft: 1.16.5
- BungeeChat:  2.2.3.1241
- Other related plugins:  BungeePerms 4.0 #129

**Comment by BrainStone** [comment]
So join and leave messages need two permissions. One on the player to even send it and one on the player who sees it.

https://github.com/AuraDevelopmentTeam/BungeeChat2/wiki/Permissions#events

**Comment by JeffHD** [comment]
All players have the 4 permissions (join, join.view, leave and leave.view) but noone receive the message. It worked once but since i switched to BungeePerms it doesn't work anymore

**Comment by BrainStone** [comment]
If it worked before and now doesn't it's an issue with your permissions plugin. That I can't help with. Sorry.
