### ISSUE TITLE
Player got an error with proxy and then when trying to chat BungeeChat gave a big error in the Proxy Server console.

### ISSUE THREAD

**Issue by AllPlayed** [AuraDevelopmentTeam/BungeeChat2#189]
#### Issue Description:
Player got an error with proxy and then when trying to chat BungeeChat gave a big error in the Proxy Server console.

#### What happens:
It seemed like a user from my server got disconnected from the proxy but not from the server that he was on, so then when he was trying to chat, BungeeChat started to shot a big error in the console.

#### Steps to reproduce:

1. Disconnect (with an error) from proxy but be connected to a server (for example, a survival one)
2. Try to chat in the server global (and local I can think) chat
3. See the error in the proxy server console

____
#### Affected Versions:

- Minecraft: 1.16.5
- BungeeChat:  2.2.3
- Other related plugins: None

#### Your most recent log or stack trace file where the issue was present: 

[Click here to see the console log](https://mcpaste.io/78603288bb6c07e6)

**Comment by BrainStone** [comment]
Have the user relog. That will fix it.
