### ISSUE TITLE
Luckperms Prefix Stacking does not apply to placeholder

### ISSUE THREAD

**Issue by Dead-Doctor** [AuraDevelopmentTeam/BungeeChat2#193]
#### What happens:
It only uses the main Luckperms prefix

#### What you expected to happen:
Response to the prefix stacking settings:
[Wiki](https://luckperms.net/wiki/Prefix-&-Suffix-Stacking) 

#### Steps to reproduce:

1. Use %prefix% placeholder in formating
2. Set "start-spacer" to something other than ""
3. It is not going to show up in game

____
#### Affected Versions: 
- BungeeChat2 
- LuckPerms

**Comment by BrainStone** [comment]
Where did you configure that? On the Bungee or the Spigot servers?

**Comment by Dead-Doctor** [comment]
> Where did you configure that? On the Bungee or the Spigot servers?

On both. I am also using an mysql database to sync prefixes.

**Comment by BrainStone** [comment]
Does the spacer show when you run `/lpb user <user> info`?

**Comment by Dead-Doctor** [comment]
> Where did you configure that? On the Bungee or the Spigot servers?

On both. It also works with the tab plugin(TAB by Neznamy which uses the placeholder API and a Bungeecord Bridge Plugin) i use.

I looked into the code from bungeechat(LuckPerms5 hook) and it only ckecks the prefix metadata.

I am also using an mysql database to sync prefixes.

**Comment by Dead-Doctor** [comment]
> Does the spacer show when you run `/lpb user <user> info`?

No

**Comment by BrainStone** [comment]
Then it's either not configured properly on the Bungee, or LP has a bug.

If that spacer shows in that command and not in BungeeChat, there's a bug.  
I believe you only have it configured correctly on the backend servers, but not on the Bungee. TAB uses the prefix data from the backend servers and not the Bungee. BungeeChat uses the data from the Bungee.

**Comment by Dead-Doctor** [comment]
Thanks. You were right.

**Comment by BrainStone** [comment]
No problem. Happy to help :)
