### ISSUE TITLE
luckperms integration doesnt work

### ISSUE THREAD

**Issue by kristupas098** [AuraDevelopmentTeam/BungeeChat2#198]
#### Issue Description: 

I copied all plugins and configs from lobby server to main server but changed servername to main_server

note: main server is nether 

#### What happens:

luckperms prefixes is shown in chat in lobby server but it uses default config in main server

#### What you expected to happen:

To show luckperms prefix in chat in main server chat

#### Steps to reproduce:

1.  honestly i dont know it supposed to work just fine
...

Configuration files:

[bungeechat]
https://gist.github.com/kristupas098/1a72c446a2e34eeed5b1dc8cc381bf47

[luckperms bungee]
https://pastebin.com/0N6LaudZ

[luckperms lobby]
https://pastebin.com/jG0YQb1S

[luckperms nether]
https://pastebin.com/iuqSiiCm

[waterfall config]
https://pastebin.com/XXhQM0uF

[lobby server.properties]
https://pastebin.com/LbhRiFpM

[nether server.properties]
https://pastebin.com/696izLk5

____
#### Affected Versions: 

- Minecraft: 1.17
- BungeeChat:  
- luckperms

#### Your most recent log or stack trace file where the issue was present: 

[waterfall latest log]
https://pastebin.com/1A00mFb1

[lobby server latest log]
https://pastebin.com/Pg86NmET

[main server latest log]
https://pastebin.com/u3eTxeq2

**Comment by BrainStone** [comment]
OMG!

I'm so sorry. I completely missed that issue!

Now onto your problem:
- The integration loads fine
- Looking at your LP configs it seems like you're not syncing your LP instances with a database. While this is not necessary it makes things easier. But for things to work the prefixes need to be assigned in the Bungee LP instance (or in all instances when using a database)
