### ISSUE TITLE
No permission message on staff chat use

### ISSUE THREAD

**Issue by VoidAngel** [AuraDevelopmentTeam/BungeeChat2#2]
When a staff member uses staff chat to talk, every player on the server without permission to view staff chat (every regular player) gets this message https://gyazo.com/e672fe8fcc003633587d5ab0d4068a6a

**Comment by BrainStone** [comment]
@VoidAngel thanks for the report. We have already fixed this feature. I'm sure shawn can give you a more recent version of the plugin.
