### ISSUE TITLE
Color format problem on links

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#203]
#### Issue Description: 

If a player tries to format a link that uses at least 2 letters as the name and at least 2 - 4 letters as the TLD with a slash at the end, then a `&r` after it will not work.

#### What happens:

![grafik](https://github.com/AuraDevelopmentTeam/BungeeChat2/assets/4140635/6b3fee0a-22a4-4316-a608-cf64e365e129)

#### What you expected to happen:

"Hello" in white, because of "&r".

#### Steps to reproduce:

1. `/msg <test user> &bte.de/&rHello`
2. `/msg <test user> &bte.deee/&r Hello`

____
#### Affected Versions: 

- Minecraft: 1.19.4
- Proxy: Waterfall 1.19 R0.1 build 521
- BungeeChat: 2.2.4.1358-DEV

**Comment by BrainStone** [comment]
Due to the way Bungee parses text with color codes, there's not much I can do unfortunately.

The only fix would be to completely reimplement chat color parsing and that's a fair bit beyond the scope.
