### ISSUE TITLE
Fast relog, random connection lost from BungeeChat

### ISSUE THREAD

**Issue by Eisengolem** [AuraDevelopmentTeam/BungeeChat2#22]
#### What happens:
okay the main problem is that if you reconetet to fast or kick yourself with another client the bungeechat does not register you und will automaticly write in the Spigot oder Bukkit-Chat. Sometimes this problem apper suddenly without relogging.

#### Affected Versions: 

Minecraft Bungeecord : 1.12
BungeeChat:
Other related plugins: ABPS, BungeeAdminTools, BungeeTablistPlus, BungeePerms, BungeeChat, SlashServer and HubCommand

#### Your most recent log or stack trace file where the issue was present: 

Failmessage: https://pastebin.com/BKxScbPT
Config: https://pastebin.com/8HgQ7Zja

**Comment by shawn-ian** [comment]
This problem does appear when your BungeeCord server has to many progresses/data to load and save (within the time that the player is loading). Your proxy most likely skip some loading and says that the player is already connected, while he or she isn't for 100%. It is also possible that you do have another problem, but this one is the most likely. 

You could check if this problem does appear while only having BungeeChat loaded while having your server running. If the problems still appear the situation described above would be your problem.
