### ISSUE TITLE
Feature request for BungeeChat

### ISSUE THREAD

**Issue by MoonGAMERZz** [AuraDevelopmentTeam/BungeeChat2#26]
I really like the idea of global chat and staff chat and how you need a permission in order to chat in certain groups or channels. A feature I would quite like to see is possibly more channels or the ability to create channels. By a channel I mean how you type /staffchat and only people with the staffchat permission can see what you say.

To expand on my idea, would it be possible for you to create a 'channel' for donors or create a channel that we can customise? Maybe we could set the permission to access that channel or set the commands to talk in that channel or alter which groups are allowed to talk in that channel. For example I would make the channel called 'Donor' and you would need the permission 'Bungeechat.Donor' to access it or be in the group donor or higher to talk in this channel.

So in essence, my feature request is that you could make configurable channels. Thank you so much and I think highly of this plugin already so don't worry if the request cannot be made.

**Comment by BrainStone** [comment]
A far more extensible and customizable system is planned for the future.

**Comment by BrainStone** [comment]
See #27
