### ISSUE TITLE
Chat: Send Url denied by default

### ISSUE THREAD

**Issue by Hodel1** [AuraDevelopmentTeam/BungeeChat2#28]
#### Issue Description: 
When i send a Link, for example mc.xygaming.de will be denied.
In global and local chat, but Private Message is this allowed.
I can't find any permission to bypass this.

#### Steps to reproduce:

1. /g mc.xyz123gaming.de
____
#### Affected Versions: 

- Minecraft: 1.7.10 - 1.12
- BungeeChat: 2.0.6.716  (on Hexacord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT)
- Other related plugins: BungeePerm, NuVotifier

#### Your most recent log or stack trace file where the issue was present: 
```
11:47:11 [INFO] [Bungee Chat] COMMAND > InfExpert1 > Hodel1: /g Guten morgen :)
11:47:11 [INFO] [Bungee Chat] GLOBAL > InfExpert1 > Hodel1: Guten morgen :)
11:47:14 [INFO] [Bungee Chat] COMMAND > InfExpert1 > Hodel1: /g test.de
11:47:14 [INFO] [Bungee Chat] GLOBAL > InfExpert1 > Hodel1: test.de
```

In my Client i get this error message:
You do not have the permissions to perform this action!

**Comment by BrainStone** [comment]
https://github.com/AuraDevelopmentTeam/BungeeChat2/wiki/Permissions

**Comment by Hodel1** [comment]
i looked already on this site.
Which permission is that?

**Comment by Hodel1** [comment]
Okay thank. In the future, it will be better for all other, to know, that anti-advertising is url and others :D
