### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by YodaBytePrograming** [AuraDevelopmentTeam/BungeeChat2#29]
I imagine you have received this a hundred times but I thought I might as well request it in case.  The feature I am requesting would be group chats. I mean more than just staff chat but also for the players. Permission support for group chats where players would need a permission to join a group chat. Again this is just an idea and adding it would make it just a step better.
Thanks for your plugin.

**Comment by BrainStone** [comment]
Yes. This has been requested many times. And as you can see in issue #27 it is planned.
