### ISSUE TITLE
Localspy - Still not working

### ISSUE THREAD

**Issue by Hodel1** [AuraDevelopmentTeam/BungeeChat2#3]
Hi,

we have updated to BungeeChat 2.0.3.1.
When i activate the Localspy and anyone write in a localchat i can't see it from another servers.

Have you the Same issue?
We are running on Hexacord for 1.7.10 support.

**Comment by BrainStone** [comment]
I'll investigate. And also thanks for mentioning that you are using Hexacord.

**Comment by shawn-ian** [comment]
Should be fixed in 2.0.3.2, sorry for having this problem ;s.

**Comment by Hodel1** [comment]
I have a note for Localspy.
Actually i get the messages both.
1. Local
2. Localspy

when on my localserver (where i am) anyone sends a message.
Screenshot: https://puu.sh/woC57/1b9b6df0cb.png

Localspy for your currentserver is not necessary.

**Comment by BrainStone** [comment]
Right. We will also fix this for the next release.

**Comment by Hodel1** [comment]
+1
Thanks for your great support :)

**Comment by BrainStone** [comment]
You're welcome! In case you didn't know we also have a discord server: https://discord.me/bungeechat  
And if you want to support us you can have a look at our patreon where you can get rewards, like even better support: https://www.patreon.com/AuraDev
