### ISSUE TITLE
Smileys

### ISSUE THREAD

**Issue by xXSchrandXx** [AuraDevelopmentTeam/BungeeChat2#30]
#### What you expected to happen:
Smileys in Chat

____
#### Affected Versions: 
- Minecraft: 1.12
- BungeeChat:  2.1.6.855

Code:
Mainclass:
`public HashMap<String, String> smileys = new HashMap<String, String>();
    for (String key : configuration.getSection("Smileys").getKeys()) {
      smileys.put(key, (String) configuration.get("Smileys."+key));
    }`
Eventclass:
`          String message = e.getMessage();
          for (Map.Entry<String, String> entry : main.getInstance().smileys.entrySet()) {
            message = message.replaceAll("(?i)" + Pattern.quote("#" + entry.getKey()), main.Loop(entry.getValue() + "&r"));
          }
          e.setMessage(message);`

Problem: How do I get your ChatEvent to get this working?

**Comment by BrainStone** [comment]
Try setting the priority to lowest or even lowest - 10

**Comment by xXSchrandXx** [comment]
worked with lowest

**Comment by BrainStone** [comment]
I'd recommend using `lowest - 10` though
