### ISSUE TITLE
1.12.2 Incompatibilities?

### ISSUE THREAD

**Issue by Fordy436** [AuraDevelopmentTeam/BungeeChat2#32]
#### Issue Description:

Updated my Bungeecord Server to Build #1273 (MC 1.12.2) and all of the connected Spigot Servers to Build #131 (MC 1.12.2). I also updated LuckPerms (a previously supported Plugin). Somewhere along this road, BungeeChat can no longer retrieve Prefixes/Suffixes from LuckPerms. Permissions are also struggling to verify since all tested commands now give the "not enough permissions" message.

#### Steps to reproduce:

1. Use Bungeecord Build #1251 (Minecraft 1.12.1)
2. Use Spigot Build #121 (Minecraft 1.12.1)
3. Use LuckPerms Build 3.2.20
4. Make a simple rank with a prefix using Luckperms using a MySQL Database and see that prefix works in game and give that rank permissions to a simple command such as Bungeechat's /msg (bungeechat.command.msg)
5. Update Bungeecord to Build #1273 (Minecraft 1.12.2)
6. Update Spigot to Build #131 (Minecraft 1.12.2)
7. Update LuckPerms to Build 3.4.15
8. The name should show, but the prefix shouldn't. /msg should also be denied (even to an OP).

#### Affected Versions:

- Minecraft: 1.12.2
- Bungeecord: 1273
- BungeeChat:  2.1.6.855
- LuckPerms: 3.4.15

**Comment by BrainStone** [comment]
Do you get any errors in the the bungee console?

Also when you run `/lpb user <you> info` and `/lp user <you> info` is the UUID the same?

**Comment by Fordy436** [comment]
No errors on the Bungeecord Console.

The lpb command doesn't exist? Should it?

**Comment by BrainStone** [comment]
Try executing the lbp command from the bungee console

**Comment by Fordy436** [comment]
"Command not found". What Plugin executes lpb? LuckPerms?

**Comment by phit** [comment]
yes if that command doesn't work luckperms didn't load

**Comment by Fordy436** [comment]
Fixed the issue. It wasnt a bug to do with Bungee chat, thank you for your quick replies anyway.

**Comment by BrainStone** [comment]
Ok. Glad you figured it out.
