### ISSUE TITLE
Local chat

### ISSUE THREAD

**Issue by CCCCarsten** [AuraDevelopmentTeam/BungeeChat2#33]
I have activated the global chat as default. How can I use the local chat (config.yml = true) now? I haven't found any command for that...

**Comment by BrainStone** [comment]
That is known an being worked on

**Comment by BrainStone** [comment]
No. Quite simply I'll work on it when II'll continue working on the plugin. No ETA on that. I just started a new job, so it's unlikely I'll be working on it in the commin months. I apologize for this inconviniece.
