### ISSUE TITLE
Other plugins which hook into the chat

### ISSUE THREAD

**Issue by CCCCarsten** [AuraDevelopmentTeam/BungeeChat2#36]
Same problem to me:

https://www.spigotmc.org/threads/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin-paid.163536/page-69#post-2734613

**Comment by BrainStone** [comment]
Well there is nothing I can really do from the technical side. You ahve the option to enable `pass-to-client-server` which makes sure the servers recieve the message. However you need to cancel the message locally.

**Comment by BrainStone** [comment]
See https://github.com/AuraDevelopmentTeam/BungeeChat2/blob/f7ed6de7ae34333c99d71cec77b0910669d4114e/src/main/resources/config.yml#L83 and https://github.com/AuraDevelopmentTeam/BungeeChat2/blob/f7ed6de7ae34333c99d71cec77b0910669d4114e/src/main/resources/config.yml#L115

**Comment by CCCCarsten** [comment]
Thank you very much!
