### ISSUE TITLE
Developing Module will not work for me

### ISSUE THREAD

**Issue by Hodel1** [AuraDevelopmentTeam/BungeeChat2#37]
I wrote an additional Module (as Plugin) for BungeeChat2.
It will be activated but not enabled in Modulemanager.

Base Code is like following:

` 	 
public class BungeeChatLocalTo extends Plugin {
	
	@SuppressWarnings("unused")
	private BungeeChat bungeeChatInstance;
	
	@Override
	public void onEnable() {
		getLogger().info("BungeeChatLocalTo started!");
		bungeeChatInstance = BungeeChat.getInstance();

		BungeecordModuleManager.clearActiveModules();
		
		BungeecordModuleManager.registerModule(new LocalToModule());
		BungeecordModuleManager.enableModules();
		BungeecordModuleManager.registerPluginModules();
		
		getLogger().info(BungeecordModuleManager.getLocalModules().toString());
		getLogger().info(BungeecordModuleManager.getActiveModuleString());
		
	}

}
	`

This Module i added will not displayed in my output.
The onEnable() Void will not executed.

did I forgot something?

Greets

**Comment by BrainStone** [comment]
First of all, don't use the implementation classes. You should just depend on the API.

Second the right way to register a module is like this:

```java
    @Override
    public void onLoad() {
        ModuleManager.registerModule(new ExampleModule());
    }
```
