### ISSUE TITLE
Strange Icon in chat

### ISSUE THREAD

**Issue by eob2000** [AuraDevelopmentTeam/BungeeChat2#40]
#### Issue Description: 
Ever since installing bungeechat the icon inn the image has been appearing in chat upon joining a server, I have looked for plugin conflicts but nothing seems to be conflicting as far as I can tell. and it only appears when bungeechat is installed.

If you need any more info please let me know. Thank You

![image](https://user-images.githubusercontent.com/17178863/33799038-aac1af84-dd1b-11e7-9f1d-203b4bd60c8e.png)

#### Affected Versions: 

- Minecraft: 1.12
- BungeeChat:  2.1.6.855
- Other related plugins:

**Comment by BrainStone** [comment]
I need your BungeeConfig

**Comment by eob2000** [comment]
[config.txt](https://github.com/AuraDevelopmentTeam/BungeeChat2/files/1545965/config.txt)

**Comment by phit** [comment]
save the file as "UTF-8 without BOM" instead of "UTF-8", assuming you are using Notepad++ that can be found under Encoding in the top menu

**Comment by eob2000** [comment]
Ive tried both UTF-8 and UTF-8-BOM, they both give the same problem

**Comment by BrainStone** [comment]
@eob2000 I apologize for this long wait, but does this issue persist? And does it persist with a new config as well?

**Comment by BrainStone** [comment]
I'll go ahead and close this. If it persists post a comment to reopen please.
