### ISSUE TITLE
[Bug]: empty messages with GlobalChat-Symbol

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#43]
#### Issue Description:

If i use the option: "GlobalChat.symbol.symbol" with e.g.
`        symbol: "!"`
I can write a empty messages in my last test.

____
#### Affected Versions:

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855

**Comment by AwesomestCode** [comment]
Wrote a patch for this. Opening pull request.
