### ISSUE TITLE
Mute bypassing due to repeated message in global/local chat

### ISSUE THREAD

**Issue by FinnChildress** [AuraDevelopmentTeam/BungeeChat2#46]
#### Issue Description: 

The /mute command still allows the player to chat as if they were not muted.

#### What happens:

The other players on the server see the message sent from MC_Legend as if the player was never muted. 

#### What you expected to happen:

The player cannot talk/is muted.

#### Steps to reproduce:

My IGN: Monkeyboys || Testing players IGN: MC_Legend
1. I do: /mute MC_Legend it gives the message saying that it worked.  (See first screenshot)
![2018-01-19_20 49 22](https://user-images.githubusercontent.com/33529688/35182932-4235dd18-fd92-11e7-8b5e-95edb4c95a9e.png)

2. MC_Legend says something gets the message that they are muted but they also see that they have sent a message as if they were not muted (See  second screenshot)
![2018-01-19_20 49 32](https://user-images.githubusercontent.com/33529688/35182934-497a9dca-fd92-11e7-9283-132beef4a4fd.png)

3. The other players on the server (AKA Monkeyboys) see the message sent from MC_Legend as if the player was never muted. (See third screenshot)
![2018-01-19_20 49 38](https://user-images.githubusercontent.com/33529688/35182935-4c26b7e8-fd92-11e7-8c05-c6511f1e57d9.png)
I know the issue is with BungeeChat because the message that everyone sees from MC_Legend has the GLOBAL > prefix

#### Affected Versions: 

- Minecraft: 1.12
- BungeeChat:  2.1.6.977-DEV
- Other related plugins: 
 This is a list of my plugin but none should affect this bug:
bungeechat bungeecommandspy bungeetablistplus liteannouncer luckpermsbungee marriagemaster nicknamerbungee serverlistplus

#### Your most recent log or stack trace file where the issue was present: 

03:27:02 [INFO] [BungeeChat] GLOBAL > Lobby > MC_Legend: Test one -Before mute
03:27:11 [INFO] [BungeeChat] GLOBAL > Lobby > Monkeyboys: I can see that chat
03:27:15 [INFO] [BungeeChat] COMMAND > Lobby > Monkeyboys: /mute MC_Legend
03:27:38 [INFO] [BungeeChat] GLOBAL > Lobby > MC_Legend: I am muted but my chat still shows 
03:27:44 [INFO] [BungeeChat] GLOBAL > Lobby > Monkeyboys: I see his chat too

**Comment by BrainStone** [comment]
I found the problem.

BungeeCommandSpy uncancels the messages canceled by BungeeChat. I'll try reaching out to their devs and get it fixed.
