### ISSUE TITLE
Bungeecord chats

### ISSUE THREAD

**Issue by AirWhistle1** [AuraDevelopmentTeam/BungeeChat2#49]
Hello everyone,

I am looking for a BUNGEECORD plugin.
The goal is that you can make as many chats as you want . For example admin chat, helper chat, moderator chat, developer chat etc.

I already tried using BungeeChat, but it's not possible.

Could someone help me?
#1AirWhistle

**Comment by BrainStone** [comment]
Not possible yet. Though similar features are planned.
