### ISSUE TITLE
[Bug]: TabCompletion use the UUID of players

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#53]
#### Issue Description: 

e.g. my ingame name is RedstoneFuture. And my UUID "ea2f0834-556d-4f3c-9c73-bb96202315df". If I write "/msg e" + *TAB* than I get my name. But not with /msg "/msg r" + *TAB*. This is confuse for the player.

The same with orther plugins: e.g. my bukkit-teleport system use the player-UUIDs if BungeeChat is installed.

#### What you expected to happen:

At normal the TAB-completion use in other server only the player-names.

#### Steps to reproduce:

--> see step 1

____
#### Affected Versions: 

- Minecraft: 1.12.2
- BungeeChat:  version 2.1.6.855
- Other related plugins: not of interest (I tested it without BungeeChat and now the bukkit - "/tp ..." command use the playername for the his TAB-completion.)

**Comment by BrainStone** [comment]
Do you have TabCompletion enabled in the BungeeChat config? (Should be a module there)

**Comment by RedstoneFuture** [comment]
At this time I activated tab-complete, yes. But a helpful tab-completition work base on the usernames and not the uuids.

**Comment by BrainStone** [comment]
I mean if Tab-Complete is disabled in the config, BungeeChat doesn't do any tabcompletion. Not even for its own commands. Meaning that the tab completion you experienced there was from another plugin.

However enabling tab complete in BungeeChat, enables it everywhere.

But generally speaking I agree, There should be a tab complete for its own commands.

So I'll change this from a bug to a suggestion.

**Comment by RedstoneFuture** [comment]
Ich hatte es aktiviert. Und es hat funktioniert. Aber es ist nutzlos, weil es auf Bungee-Seite die Vervollständigung nur basierend auf die UUIDs anwendet. Auf Bungee-Seite mischt sich da bei mir kein anderes Plugin ein.

**Comment by BrainStone** [comment]
Tab Completion has been removed completely, as it is a pointless feature and just causes issues and confusion.
