### ISSUE TITLE
Feature requests: Clear chat command and separate permission for using formats in chat

### ISSUE THREAD

**Issue by Darunia18** [AuraDevelopmentTeam/BungeeChat2#6]
Currently, the only way to clear chat is to lock the chat. Could you add a command to be able to clear chat without locking chat?

Also, giving users the permission bungeechat.chat.colors also gives them access to use chat formats like bold, italics, underscore, and magic. Is it possible to make those a separate permission?

**Comment by BrainStone** [comment]
The clear command should be doable. Having separate permissions for colors and formats might be difficult though. We will have a look.

**Comment by shawn-ian** [comment]
ClearChat command is plannend to be added into a coming update. We indeed should have a better look at separating color codes from format codes.

**Comment by BrainStone** [comment]
Clear chat has been added.

**Comment by BrainStone** [comment]
The code for individual permissions for all color and format codes is complete too, Which means it will be available in the next release!
