### ISSUE TITLE
MOTD Not Sending and Reload Errors

### ISSUE THREAD

**Issue by InfinityAspire** [AuraDevelopmentTeam/BungeeChat2#61]
#### Issue Description: 
MOTD not sending to players and errors on /bungeechat reload

#### What happens:
BungeeChat errors on reloads and doesn't send the MOTD to players at all.

#### What you expected to happen:
The plugin to reload correctly and send the MOTD to players with correct permissions

#### Steps to reproduce:

1. Disable all features except for MOTD
2. Attempt to run /bungeechat reload
3. Watch the fireworks in console
...

____
#### Affected Versions: 

- Minecraft: 1.12.2
- BungeeChat:  2.1.6
- Other related plugins: VentureChat 2.12.2

#### Your most recent log or stack trace file where the issue was present: 

[https://pastebin.com/2kgcpx2N](https://pastebin.com/2kgcpx2N)

**Comment by phit** [comment]
version is in the log, they are running latest build 178

**Comment by BrainStone** [comment]
Hm. The bug looks like it's originating from Waterfall.

**Comment by InfinityAspire** [comment]
I would but your maven is down, your github triggers MalwareBytes and no updates have been pushed to Spigot

**Comment by BrainStone** [comment]
I meant of Waterfall 😬

**Comment by InfinityAspire** [comment]
Just got a chance to test. Still broken, no changes in anything

**Comment by BrainStone** [comment]
Pretty sure it's fixed by now (with the latest version of BungeeChat at least).
