### ISSUE TITLE
Disable for some servers

### ISSUE THREAD

**Issue by meandpiggy** [AuraDevelopmentTeam/BungeeChat2#62]
This is not an issue, this is a question or a feature request.

What I want is a way to be able to disable the Chat Format for a certain server, such as this:

Hub Chat: [Owner] meandelsa: Hi
KitPvP Chat: [Owner] meandelsa: Hi
BedWars Chat: (The default Minecraft chat)

Thanks!

**Comment by BrainStone** [comment]
This is planned for 2.2.0.
