### ISSUE TITLE
Error on Launch

### ISSUE THREAD

**Issue by TheTacobite** [AuraDevelopmentTeam/BungeeChat2#63]
#### Issue Description: 
Read Below

#### What happens:
https://hastebin.com/kocujuzuyi.rb

#### What you expected to happen:
N/A

#### Steps to reproduce:

1.  Launch plugin

#### Affected Versions: 

- Minecraft: 1.12.2
- BungeeChat:  2.1.6
- PowerfulPerms: 4.5.2
- Other related plugins: 

#### Your most recent log or stack trace file where the issue was present: 

https://hastebin.com/kocujuzuyi.rb
```

**Comment by BrainStone** [comment]
I'm sorry, but it appears that your log has disappeared. I'd recommend using https://gist.github.com/, as that site is confirmed to not delete pastes.

Sorry for the inconvinience and late response.

**Comment by BrainStone** [comment]
No response in a year. Closing this.
