### ISSUE TITLE
Color &5 doesn't work with COLOR.dark_purple Permission in chat and terminal

### ISSUE THREAD

**Issue by LinuxScriptingsh** [AuraDevelopmentTeam/BungeeChat2#64]
#### Issue Description:
The Color &5 doesn't work in chat and console

#### What happens:
It pastes &5 "Message" in Chat

#### What you expected to happen:
It should paste COLOR.dark_purple "Message". 
Just like COLOR.dark_red "Message".

____
#### Affected Versions:

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855

**Comment by BrainStone** [comment]
Do you happen to use LuckPerms?

If so, could you run the command `/lpb verbose record bungeechat`, the try the message and then run `/lpb verbose paste` and post the link that the plugin outputs here?

**Comment by LinuxScriptingsh** [comment]
No, we use BungeePerms.

**Comment by BrainStone** [comment]
Can you try `/bungeeperms debug true`, then chat with that color, `/bungeeperms debug false?` and screenshot the output?

**Comment by LinuxScriptingsh** [comment]
![2018-06-22_20 12 03](https://user-images.githubusercontent.com/39629672/41792280-9b275174-7658-11e8-97d4-51dd4376fe5a.png)

Another Owner executed those two commands you posted. The upper one is with debug true and the bottom one with debug false

**Comment by BrainStone** [comment]
I need the debug output. I think it would be helpful if you also included a color that works.

**Comment by BrainStone** [comment]
That's still not the debug log. It should display the permission checks.

**Comment by LinuxScriptingsh** [comment]
Hi Brainstone
I'm sorry that I wasted you time with this "Issue", but the technician decided to use another Plugin.
Perhaps it wasn't your Plugin that didn't the Job. Maybe it was Bungeeperms.
But thank you for your patience

~LinuxScriptingsh
