### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Trucasy0** [AuraDevelopmentTeam/BungeeChat2#67]
Just a simple question:

Does this plugin support multibungee?

**Comment by BrainStone** [comment]
Do you have a link?

**Comment by phit** [comment]
probably means multiple bungeecord instances

**Comment by BrainStone** [comment]
In that case, no. No way to sync the chat between multiple instances at this time

**Comment by BrainStone** [comment]
Also in case it is plugin or similar, there certainly isn't support from my side.

I'll close this issue. If you have further questions, feel free to add details and I'll reopen. Also if you have Discord, you can get in touch with me much easier by using my discord server: https://discord.me/bungeechat

**Comment by BrainStone** [comment]
I'll close this for now. If you still have questions about it, post here again and IU'll reopen it.
