### ISSUE TITLE
Private Message does not work

### ISSUE THREAD

**Issue by MinecraftTim123** [AuraDevelopmentTeam/BungeeChat2#7]
![screenshot_20170701-232500](https://user-images.githubusercontent.com/26803527/27765581-a7c163fe-5eb5-11e7-9cf1-20287ebefd74.png)
![screenshot_20170701-232504](https://user-images.githubusercontent.com/26803527/27765612-8a1aafc6-5eb6-11e7-8fc5-dc8b83500106.png)

There are not any warnings in the console (picture 1). As you can see, there arrive no private messages between server - player, player - player (one hand with other groups and otherhand with the same group!) I am using BungeeChat (Version 2.0.6.716) with BungeeCord under 1.12.!

Please help me!

Thank you

**Comment by BrainStone** [comment]
Stop the bungee, delete the datadir of bungeechat and restart. Should be fixed after that.

**Comment by MinecraftTim123** [comment]
Nope, does not work. I deleted my BungeeChat-folder, but PM does not work


![screenshot_20170701-235201](https://user-images.githubusercontent.com/26803527/27765691-e1c75ec0-5eb8-11e7-9b8a-31d03c8a0b85.png)
![20170701_235242](https://user-images.githubusercontent.com/26803527/27765693-ede654cc-5eb8-11e7-9bb9-03f68df60d57.png)

**Comment by BrainStone** [comment]
If you have Discord, you can join our server at https://discord.me/bungeechat

**Comment by BrainStone** [comment]
Issue were wrong keys in the config.
