### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Matthysse** [AuraDevelopmentTeam/BungeeChat2#70]
Please add placeholder creator, just simple placeholders statics like if i do %money% it give the coin symbol of the server

**Comment by BrainStone** [comment]
What's stopping you from just writing out the text in the format?

**Comment by Matthysse** [comment]
Which format? Sorry i'm french i don't understand very well...

**Comment by BrainStone** [comment]
You have chat formats. Like instead `%name% %money%` you could also just use `%name% $`.

**Comment by Matthysse** [comment]
My money symbol isn't $ but a special symbol (alt+..)

**Comment by BrainStone** [comment]
I don’t see how a placeholder would make that easier. As you would have to put it in the config somewhere. So just put the symbol where you want to have it.
