### ISSUE TITLE
Error when sending a message

### ISSUE THREAD

**Issue by ApertureDevelopment** [AuraDevelopmentTeam/BungeeChat2#71]
#### Issue Description:

Chat messages wont get send and commands crash the server.

#### What happens:

A error gets printed out in the console.

#### What you expected to happen:

``<Rainbow_Dash1342>: Hello World!``

#### Steps to reproduce:

1. Install the plugin on bungeecord
2. Restart

____
#### Affected Versions:

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855

#### Your most recent log or stack trace file where the issue was present: 

https://gist.github.com/ApertureDevelopment/a4e0f2800fb18b61b3707f1c99b59ede

**Comment by BrainStone** [comment]
I’m sorry that’s not the full error message. The most important part, namely the exception ist missing

**Comment by ApertureDevelopment** [comment]
Thats litterally everything that is in the console. I will check the log file if it says more

**Comment by BrainStone** [comment]
There’s missing the line above it. Which is the actual error

**Comment by ApertureDevelopment** [comment]
Here you go. I couldn't find it in the console, but the log file said more: 

https://gist.github.com/ApertureDevelopment/77fa2d409d699f515b118cb34361d0eb

**Comment by BrainStone** [comment]
Looks like an outdated version of bungeeperms is being used. Can you try to use the latest version?

**Comment by ApertureDevelopment** [comment]
The 3.0 Development Version? I use the version from their website

**Comment by BrainStone** [comment]
Oh? There’s been some actual development? Neat. Well then the opposite is the case. Then your version is too new and you need to use the latest release.

**Comment by BrainStone** [comment]
Since there hasn't been an update here, I'll close this. I'll update the support as soon as I'll continue developing.
