### ISSUE TITLE
[IDEA] 1.13 New Command UI

### ISSUE THREAD

**Issue by Chazotu** [AuraDevelopmentTeam/BungeeChat2#72]
Update the Plugin to make usage of the new Command UI implemented in 1.13 .

**Comment by BrainStone** [comment]
I will add this when I continue working on the plugin and it won’t break backwards compatibility and bungee allows it.

**Comment by BrainStone** [comment]
Recently added

**Comment by BrainStone** [comment]
Will be in the 2.2.2 release
