### ISSUE TITLE
BungeeChat support faction

### ISSUE THREAD

**Issue by amigo127** [AuraDevelopmentTeam/BungeeChat2#73]
sorry i'm french and i don't understand :rofl: 

The faction name on prefix

- Minecraft: 1.8
- BungeeChat:  latest for 1.8
- Other related plugins: faction

**Comment by BrainStone** [comment]
Not possible, because the bungee cannot access the faction information. If you manage to store the faction data in your permissions plugin's prefixes and use a permissions plugin like LuckPerms you could achieve it.

Also if you're having issues with the language, try: https://deepl.com/
