### ISSUE TITLE
Permission Nodes for chat privileges

### ISSUE THREAD

**Issue by Brianetta** [AuraDevelopmentTeam/BungeeChat2#74]
#### Issue Description:
It should be possible to mute players by means of permission nodes. At least one node for local chat, but it might be necessary to have nodes for global chat if that has been configured as the default channel.

**Comment by BrainStone** [comment]
Shouldn't be too hard to implement. Can see this in 2.2.0

**Comment by BrainStone** [comment]
This was added in 2.2.0
