### ISSUE TITLE
False negatives with /msg and similar usernames

### ISSUE THREAD

**Issue by Morsmorse** [AuraDevelopmentTeam/BungeeChat2#75]
#### Issue Description: 
When 2 Players have a similar name (in this case `user_` and `user__`) You can't write `user_` private messages anymore. `User__` works as usual though. You'll get a "User not found" Error

#### What you expected to happen:
The Plugin should check if `user_` matches a username exactly and use this user and if not look for similar usernames to target.

____
#### Affected Versions: 

- Minecraft: 1.13
- BungeeChat:  2.1.6.994-SNAPSHOT
- Bungee: 1.13-SNAPSHOT:715ex07:1344

**Comment by BrainStone** [comment]
Just to be sure, can you try with the latest dev build?

**Comment by Morsmorse** [comment]
Yes still an issue with 2.1.7.1014-DEV

**Comment by BrainStone** [comment]
https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.1.7.1095-DEV/BungeeChat-2.1.7.1095-DEV.jar

This should fix it.
