### ISSUE TITLE
/ignore does not work

### ISSUE THREAD

**Issue by Mario359** [AuraDevelopmentTeam/BungeeChat2#77]
#### Issue Description: 
When I do /ignore add <Player>, I keep seeing the messages of the player (in global & local)

#### What happens:
No error, the plugin tells me that I ignore this player yet I keep seeing his messages, and he does not have permission: bungeechat.chat.bypass.ignore

#### What you expected to happen:
Do not see messages

#### Steps to reproduce:

1. /ignore add <Player>
2. The ignored player must speak in the chat

____
#### Affected Versions: 

- Minecraft: 1.15.2
- BungeeChat: 2.1.7.1071-DEV
- Other related plugins: EssentialsX-Chat

**EDIT**: Messages from an ignored player are not displayed when it's a private message (/msg)

**Comment by andrei923** [comment]
any update with a fix?

**Comment by BrainStone** [comment]
Not yet

**Comment by soerili** [comment]
Any update on that bug?

**Comment by BrainStone** [comment]
Nothing new. Haven't found the time to work on this.

**Comment by BrainStone** [comment]
Please test with this version: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.1.7.1112-DEV/BungeeChat-2.1.7.1112-DEV.jar

Note there's a config option to select whether you want normal chat messages to be blocked or not. And it defaults to false.
