### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by bwhybrow23** [AuraDevelopmentTeam/BungeeChat2#78]
#### Issue Description: 
Everything to do with the plugin is working fine and it functions like it normally should, but anytime it is involved with something then the console gets spammed with the same message. 

`[17:51:39 ERROR]: Wed Oct 31 17:51:39 CDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

#### What happens:
I get an error as described above

#### What you expected to happen:
No error to appear in console

#### Steps to reproduce:

1. Do anything that involves BungeeChat

____
#### Affected Versions: 

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855
- Other related plugins: MySQL 5.7

#### Your most recent log or stack trace file where the issue was present: 

https://hastebin.com/azijicagev.md

**Comment by BrainStone** [comment]
There's now a config option to disable SSL, when it's not supported by the server, as it is the case here.

**Comment by joeridukker** [comment]
I tried to get rid of this SSL message using 
AccountDatabase {
    credentials {
        database=BungeeChat
        ip="0.0.0.0"
        password="P@ssw0rd_"
        # The MySQL default port is 3306. If no port is given, use 3306
        port=3306
        tablePrefix="BungeeChat_"
        user=User
    }
    enabled=false
    # This setting allows you to define extra properties for connections.
    # 
    # By default, the following options are set to enable utf8 encoding.
    #   characterEncoding=utf8
    #   useUnicode=true
    # 
    # You can also use this section to disable SSL connections, by setting:
    useSSL=false
    #   verifyServerCertificate=false
    properties {
        characterEncoding=utf8
        useUnicode=true
    }
}
but this did not get rid of it

**Comment by BrainStone** [comment]
Can you join my Discord?
I'd like to do some 1on1 debugging

https://discord.me/bungeechat
