### ISSUE TITLE
[Idea] Add a character to write in staffchat

### ISSUE THREAD

**Issue by Totten98** [AuraDevelopmentTeam/BungeeChat2#83]
Hello,
I would like to see, like for the global chat, the possibility to write in staffchat with a character in the begin of the message.
Example: (!This message goes to staff)
Along with the already existing command /sc.

I hope you understand what I mean, thanks for your attention.
Best regards.

**Comment by fjeddy** [comment]
+1 Great idea, would make it much simpler.
