### ISSUE TITLE
Add permission to block usage of chat

### ISSUE THREAD

**Issue by jewome62** [AuraDevelopmentTeam/BungeeChat2#86]
#### Issue Description: 
I have a role visitor. for someone who did'nt make candidate. (so don't accept the rules)
So this person can not build and talk with other

So, it will be cool to have a permission to
allow ou deny (as you want) in the localchat

Thanks

PS: I currently on latest dev version

**Comment by jewome62** [comment]
@BrainStone I can try make a PR
But do you prefer add a permission to : 
- Allow to talk into chat (but it's a BC from the current workflow but at the same time, the Dev version is for a new major version 3.0)
Proposal : bungeechat.localchat
- Or to deny (but it's against the meaning of all the permission of bungeechat)
Proposal : bungeechat.localchat.deny

**Comment by BrainStone** [comment]
Please use the permission `bungeechat.command.<channel>.chat`. Like `bungeechat.command.staffchat.chat`

**Comment by jewome62** [comment]
:+1:

**Comment by jewome62** [comment]
Fixed to 2.2.1
permission `bungeechat.command.local`

**Comment by BrainStone** [comment]
That’s already in 2.2.0

**Comment by jewome62** [comment]
Yes, but that's block command too.
So the permission is not usable ;D
