### ISSUE TITLE
Plugin acting weird, events are confused...

### ISSUE THREAD

**Issue by VirgilFabre** [AuraDevelopmentTeam/BungeeChat2#87]
### Description

I changed nothing over the night and only I have the permissions, BungeeChat started to act really weird.
Chat message for switching server is now the enter network message.
If you're new switch server you'll have the enter network message AND the welcome every time.
And weirdly enough it only works for me (I didn't disconnect since 2 days that might be why the plugin remember how to work properly with me)...

Really weird behavior....

### Steps to reproduce:

No clue, happened over night randomly.

____
### Affected Versions

- Minecraft: 1.14.4
- Spigot: 1.14.4-R0.1 (Latest)
- BungeeChat: 2.1.6.855
- BungeeChat:  1.14
![q8I7cl 1](https://user-images.githubusercontent.com/40531871/62149202-2f1b4e00-b2c9-11e9-9e62-c23022e04a71.jpg)
![xTbYW9 1](https://user-images.githubusercontent.com/40531871/62149270-54a85780-b2c9-11e9-8b6c-6d07bf557b81.jpg)
![fu0Q51 1](https://user-images.githubusercontent.com/40531871/62149330-7acdf780-b2c9-11e9-919a-bbf5a60378e7.jpg)
![xDH6oJ 1](https://user-images.githubusercontent.com/40531871/62149148-1317ac80-b2c9-11e9-9dde-752822540b4d.jpg)

**Comment by BrainStone** [comment]
Pretty sure this fixed in the dev versions.
