### ISSUE TITLE
Double connection crash plugin

### ISSUE THREAD

**Issue by VirgilFabre** [AuraDevelopmentTeam/BungeeChat2#88]
If we log in then we login with another account, even tho it doesn't work the plugin crash
My player wanted to connect to localhost at the same time as my server and he created an error

![yEhRfq 1](https://user-images.githubusercontent.com/40531871/62177875-9ad6d880-b314-11e9-9b74-9a8487fd2a08.jpg)

Second error I post in 24h...

**Comment by BrainStone** [comment]
Pretty sure this fixed in the dev versions.

**Comment by VirgilFabre** [comment]
Maven:
Releases: https://maven.aura-dev.team/repository/auradev-releases/
Snapshots: https://maven.aura-dev.team/repository/auradev-snapshots/


Product logo  
Nexus Repository Manager
OSS 3.15.2-01
 Repository imageRepository auradev-snapshots
This maven2 hosted repository is not directly browseable at this URL.

Please use the component browser or asset browser to inspect the contents of this repository.

**Comment by BrainStone** [comment]
https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.1.7.1053-DEV/BungeeChat-2.1.7.1053-DEV.jar
