### ISSUE TITLE
Chatlogging Filter Option

### ISSUE THREAD

**Issue by nuttah** [AuraDevelopmentTeam/BungeeChat2#9]
There should be a option which filters out the logging for certain commands into the chat log. 
So one parameter and one array with commands.
In my case Authme logins are chatlogged and could be misused by third persons who have access to the chatlog-file e.g.

Here's an example for the config.yml

`    ChatLogging:`
`      enabled: true`
`      privateMessages: true`
`      console: true`
`      file: true`
`      filtering: true`
`      filteredcommands:`
`        - login`

**Comment by shawn-ian** [comment]
Seems like a great idea. Not sure if this would be in the next release (2.1) yet, but the feature will be added for sure.

**Comment by BrainStone** [comment]
The `filtering` flag can be left out. But it is a good idea.

**Comment by BrainStone** [comment]
@nuttah It isn't done yet. We just published the source. And our old tracking system used different IDs
