### ISSUE TITLE
AutoBroadcast not working if server list is enabled

### ISSUE THREAD

**Issue by xISYx** [AuraDevelopmentTeam/BungeeChat2#91]
#### What happens:

AutoBroadcast don't work when I enable the server list 

    AutoBroadcast {
        enabled=true
        interval="30s"
        messages=[]
    }
    GlobalChat
        passToClientServer=true
        serverList {
            enabled=false
            list=[
                CityBuild,
                lobby,
                cbc,
                Paintball,
                bedwars,
                Farm,
                knockback,
                SkyPvP,
                Labor,
                GamerzNetwork,
                GamerzNetworkLobby,
                Murder
            ]
        }
    }

**Comment by BrainStone** [comment]
Looking at it I think you just have no messages defined. The server list is off.

Closing this. If it wasn't a config mess up, please reopen.
