### ISSUE TITLE
AutoBroadcasting doesn't do clickable links

### ISSUE THREAD

**Issue by Pato05** [AuraDevelopmentTeam/BungeeChat2#92]
#### Issue Description: 
If you put a link in the AutoBroadcast module, that link won't be clickable

#### What happens:
Link not clickable

#### What you expected to happen:
Clickable Link

#### Steps to reproduce:

1. Enable AutoBroadcasting module
2. Put a link in the message
...

____
#### Affected Versions: 

- Minecraft: 1.14
- BungeeChat:  2.1.6.855
- Other related plugins: 

#### Your most recent log or stack trace file where the issue was present: 

```
<!-- Or stack trace here (Remove this if you don't put anything here!) -->
```

**Comment by JasonHorkles** [comment]
Links seem to work fine with 2.1.7.1067

**Comment by BrainStone** [comment]
I didn't do anything. xD
Most likely Bungee did that. (which I was hoping for in the first place to be honest)

**Comment by Pato05** [comment]
lmao almost 1 year after

**Comment by BrainStone** [comment]
That's how things are at times.

Btw, if you're using a recent version of Bungee, be sure to grab the latest dev version or use 2.1.6.

**Comment by Pato05** [comment]
I don't even have a server anymore, I had it in that period.
