### ISSUE TITLE
Database connection times out

### ISSUE THREAD

**Issue by gamebuddiesempire** [AuraDevelopmentTeam/BungeeChat2#93]
#### Issue Description:
After the server has been running idly for a while, the database connection no longer works. 

#### What happens:
[Error log](https://pastebin.com/MDTWTCa0)

#### What you expected to happen:
The database connection to be persistent or a new connection to be established.

#### Steps to reproduce:

1. Start the BungeeCord server with BungeeChat.
2. Wait a few minutes without anyone logging in or out.
3. Join the server.
____
#### Affected Versions:

- Minecraft: 1.14.4
- BungeeChat: 2.1.6.855

#### Additional information:
I'm happy to edit the configuration files if I can fix it that way. Maybe I missed an option to set the timeout or make the connection persistent? If so, please explain how to do this.

**Comment by BrainStone** [comment]
Can you try to use the latest dev version?  
https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/bungeechat/BungeeChat/2.1.7.1060-DEV/BungeeChat-2.1.7.1060-DEV.jar

Be aware that the config format changed, though everything should be migrated automatically.

**Comment by gamebuddiesempire** [comment]
Thank you for your quick response. I've replaced the jar file as you suggested, but still get a similar error: https://pastebin.com/XSar1XPF

**Comment by BrainStone** [comment]
Well, sorry for the late response, I became very busy with other stuff and forgot about this issue.

I looked into the issue and it seems that the `wait_timeout` of your MySQL server is set too low. Try increasing that value.

And from the research I did, this is not caused by my plugin, nor can I add any work arounds to make it work.
