### ISSUE TITLE
Prefix disappears for an user + huge error when they type something in chat

### ISSUE THREAD

**Issue by derMiepz** [AuraDevelopmentTeam/BungeeChat2#95]
#### Issue Description: 
Title says everything

#### What happens: 
User losses prefix in chat and a huge error message appears in the console

#### What you expected to happen: 
User keeps their prefix when typing in chat w/o any errors

#### Steps to reproduce: 
No steps unfortunately. Just appeared and disappeared out of nothing

____
#### Affected Versions:

- Minecraft: 1.14.4 (CraftBukkit version git-Spigot-56f8471-56118c6 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT))
- BungeeChat:  BungeeChat-2.1.6.855
- Other related plugins: BungeeTabListPlus-2.8.11, BungeeTeleport (source form GitHub, compiled myself due to the version of Spigotmc being for 1.13), LuckPerms-Bungee-4.4.31, movemenow-1.2-17, ServerListPlus-3.4.8-Universal

#### Your most recent log or stack trace file where the issue was present: 

Error only: https://gist.github.com/derMiepz/56d969a2a7e29fe5b01fd8b079b07341
Full log: https://gist.github.com/derMiepz/719ff5d17e1f3c338efee5944fd23a80

**Comment by BrainStone** [comment]
Fixed in the latest dev version
