### ISSUE TITLE
Bungeechat does not stop chats from sending

### ISSUE THREAD

**Issue by V3x1Dev** [AuraDevelopmentTeam/BungeeChat2#99]
#### Issue Description: 
When using things such as Staffchat or global chat the message is sent to said module but the real chat message is sent anyway.

#### What happens:
When you toggle Staffchat and send a message the Staff message goes through but the real chat message from vanilla minecraft is still sent 

#### What you expected to happen:
The message from minecraft does not send and the staff message is used so players cant see 

#### Steps to reproduce:

1. Install Bungeechat on Bungee
2. Install Luckperms api extention for outdated api
3. Run server
...

____
#### Affected Versions: 

- Minecraft: 1.14.4
- BungeeChat: 2.1.6
- Other related plugins: luckperms

#### Your most recent log or stack trace file where the issue was present: 
https://pastebin.com/MXn23QRw

**Comment by BrainStone** [comment]
Did you enable `passToClientServer`? 
If so disable it.

**Comment by V3x1Dev** [comment]
Oh yeah thanks
